"""empty message

Revision ID: f31c45870f71
Revises: ae02e5cc0554
Create Date: 2024-10-27 20:39:30.354343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f31c45870f71'
down_revision: Union[str, None] = 'ae02e5cc0554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('job')
        batch_op.drop_column('salary')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('job', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
